### ISSUE TITLE
Bad/missing documentation

### ISSUE THREAD

**Issue by dgtlmoon** [setezzy/image-retrieval#3]
What is the difference with `python ./retrieval_.py  -h` versus `python ./retrieval.py  -h`

And you need to explain in your README.md what to put for `threshold` and why.. is it an integer or float or?? and what does it mean?

```positional arguments:
  threshold             threshold for determining neuron activated
  {rotate,erosion,dilation}

```

**Comment by setezzy** [comment]
You could just ignore the parameter "threshold". It is for my another experiment. And, as explained in README, retrieval_.py is an example to use your own created dataset on disk as inputs.
